package org.example.Model;

public enum GuestNationalities {
    UNITED_STATES("United States"),
    CANADA("Canada"),
    MEXICO("Mexico"),
    BRAZIL("Brazil"),
    ARGENTINA("Argentina"),
    COLOMBIA("Colombia"),
    PERU("Peru"),
    VENEZUELA("Venezuela"),
    CHILE("Chile"),
    ECUADOR("Ecuador"),
    GUATEMALA("Guatemala"),
    CUBA("Cuba"),
    HONDURAS("Honduras"),
    BOLIVIA("Bolivia"),
    PARAGUAY("Paraguay"),
    URUGUAY("Uruguay"),
    PANAMA("Panama"),
    COSTA_RICA("Costa Rica"),
    DOMINICAN_REPUBLIC("Dominican Republic"),
    PUERTO_RICO("Puerto Rico"),
    JAMAICA("Jamaica"),
    TRINIDAD_AND_TOBAGO("Trinidad and Tobago"),
    EL_SALVADOR("El Salvador"),
    NICARAGUA("Nicaragua"),
    BAHAMAS("Bahamas"),
    BELIZE("Belize"),
    GUYANA("Guyana"),
    SURINAME("Suriname"),
    BARBADOS("Barbados"),
    SAINT_LUCIA("Saint Lucia"),
    GRENADA("Grenada"),
    SAINT_VINCENT_AND_THE_GRENADINES("Saint Vincent and the Grenadines"),
    ANTIGUA_AND_BARBUDA("Antigua and Barbuda"),
    SAINT_KITTS_AND_NEVIS("Saint Kitts and Nevis"),
    DOMINICA("Dominica"),
    CANADIAN("Canadian"),
    MEXICAN("Mexican"),
    AMERICAN("American"),
    BRAZILIAN("Brazilian"),
    ARGENTINIAN("Argentinian"),
    COLOMBIAN("Colombian"),
    PERUVIAN("Peruvian"),
    VENEZUELAN("Venezuelan"),
    CHILEAN("Chilean"),
    ECUADORIAN("Ecuadorian"),
    GERMANY("Germany"),
    FRANCE("France"),
    UNITED_KINGDOM("United Kingdom"),
    ITALY("Italy"),
    SPAIN("Spain"),
    NETHERLANDS("Netherlands"),
    BELGIUM("Belgium"),
    SWITZERLAND("Switzerland"),
    SWEDEN("Sweden"),
    DENMARK("Denmark"),
    NORWAY("Norway"),
    FINLAND("Finland"),
    POLAND("Poland"),
    AUSTRIA("Austria"),
    GREECE("Greece"),
    TURKEY("Turkey"),
    INDIA("India"),
    CHINA("China"),
    JAPAN("Japan"),
    SOUTH_KOREA("South Korea"),
    AUSTRALIA("Australia"),
    NEW_ZEALAND("New Zealand"),
    SOUTH_AFRICA("South Africa"),
    EGYPT("Egypt"),
    NIGERIA("Nigeria"),
    KENYA("Kenya"),
    MOROCCO("Morocco"),
    SAUDI_ARABIA("Saudi Arabia"),
    UNITED_ARAB_EMIRATES("United Arab Emirates"),
    ISRAEL("Israel"),
    IRAN("Iran"),
    RUSSIA("Russia"),
    UKRAINE("Ukraine");

    private final String displayName;

    GuestNationalities(String displayName) {
        this.displayName = displayName;
    }

    public String getDisplayName() {
        return displayName;
    }
}
